# This configuration corresponds to Reference Model

# ----------------------------------------------------------------------------
# Basic setup
# ----------------------------------------------------------------------------
debug: False
use_multiprocessing: False
seq: "10"
dataset: kitti_odom # [kitti_odom, kitti_raw]
seed: 4869
frame_step: 1
image:
  height: 192
  width: 640
  # height: 370
  # width: 1226
  ext: jpg

directory:
  result_dir: result/tmp/0
  img_seq_dir: dataset/kitti_odom/odom_data_jpg/
  # img_seq_dir: dataset/kitti_odom/kitti_odom_rv/
  gt_pose_dir: dataset/kitti_odom/gt_poses/
  depth_dir: #../robust-vo/dataset/kitti_odom/depth/
  # img_seq_dir: dataset/kitti_raw
  # gt_pose_dir: dataset/kitti_raw
  # depth_dir: /home/hyzhan/harddisk_local/DOM/result/kitti_raw_gt_depth

# ----------------------------------------------------------------------------
# tracking options
# ----------------------------------------------------------------------------
tracking_method: PnP
  # 3: hybrid
  # 1: PnP

e_tracker:
  ransac:
    reproj_thre: 0.2
    repeat: 3
  validity:
    method: GRIC # [flow, homo_ratio, GRIC]
    thre: 
  kp_src: kp_best # [kp_best, kp_list, kp_rigid]

pnp_tracker:
  ransac:
    iter: 1000
    reproj_thre: 1
    repeat: 3
  kp_src: kp_best # [kp_best, kp_list, kp_rigid]

# translation scale
scale_recovery:
  method: simple # [single; iterative]
    # - dfvo: selcted kps 
  ransac:
    method: depth_ratio # [abs_diff, depth_ratio]
    min_samples: 3
    max_trials: 100
    stop_prob: 0.99
    thre: 0.1
  kp_src: kp_best # [kp_best, kp_list, kp_rigid]

# ----------------------------------------------------------------------------
# Deep Optical Flow
# ----------------------------------------------------------------------------
deep_flow:
  half_flow: False
  online_finetune:
    enable: False
    lr: 0.000001
    num_frames: 50
    loss:
      flow_consistency: 0.005
      flow_smoothness: 0.1
  forward_backward: True
  num_kp: 2000
  network: liteflow  
    # liteflow: LiteFlowNet
  # flow_net_weight: model_zoo/optical_flow/LiteFlowNet/network-default.pytorch
  # flow_net_weight: model_zoo/optical_flow/LiteFlowNet/network-default-doubled.pytorch
  # flow_net_weight: model_zoo/optical_flow/LiteFlowNet/network-kitti.pytorch
  # flow_net_weight: model_zoo/optical_flow/UnLiteFlowNet/kitti_odom/mono_640x192/flow.pth
  # flow_net_weight: /home/hyzhan/harddisk_local/DF-VO/robust-vo/deep_depth/monodepth2/checkpoint/kitti/flow/exp_2/0/10/M_640x192/models/weights_5/flow.pth
  batch_size: 1
  precomputed_flow: #tmp/result/flow/kitti_odom/liteflow_default/{}/npy

crop:
  depth_crop: [[0.3, 1], [0, 1]]
  flow_crop: [[0, 1], [0, 1]]

# ----------------------------------------------------------------------------
# Deep single-view depth
# ----------------------------------------------------------------------------
depth:
  depth_src: # (blank: deep model inference; 0: GT depth)
  max_depth: 50 # [10/50/200]
  min_depth: 0
  pretrained_model: model_zoo/depth/kitti_odom/stereo/
  # pretrained_model: model_zoo/depth/kitti_odom/mono_sc/
  # pretrained_model: model_zoo/depth/kitti_odom/mono/

# ----------------------------------------------------------------------------
# Deep two-view pose
# ----------------------------------------------------------------------------
pose_net:
  enable: False
  pretrained_model: model_zoo/pose/kitti_odom/stereo/
  # pretrained_model: model_zoo/pose/kitti_odom/mono_sc/
  # pretrained_model: model_zoo/pose/kitti_odom/mono/

# ----------------------------------------------------------------------------
# Keypoint selection
# ----------------------------------------------------------------------------
kp_selection: 
  local_bestN:
    enable: True
    num_row: 10
    num_col: 10
    num_bestN: 2000
    score_method: flow # [flow, flow_depth, flow_ratio]
    thre: 0.1
  bestN:
    enable: False
    num_bestN: 2000
  sampled_kp:
    enable: False
  rigid_flow_kp: 
    enable: False
    num_row: 10
    num_col: 10
    num_bestN: 2000
    score_method: flow # [flow, flow_depth]
    rigid_flow_thre: 3
    optical_flow_thre: 0.1

    
  depth_consistency:
    enable: False
    thre: 0.05
  flow_consistency:
    enable: True
    thre: 0.1

# ----------------------------------------------------------------------------
# Visualization
# ----------------------------------------------------------------------------
visualization:
  enable: True
  save_img: True
  kp_src: kp_best
  flow: 
    vis_forward_flow: True
    vis_backward_flow: True
    vis_flow_diff: True
  kp_match:
    kp_num: 100  # -1 for using all
    vis_temp: 
      enable: True
    vis_side: 
      enable: True
      inlier_plot: False

  depth:
    # vis_full_disp: True
    depth_disp: disp
    use_tracking_depth: False
  mask:
    vis_masks: True
  trajectory:
    vis_traj: True
    draw_scale: 0.6
    mono_scale: 1 #5.4; 0.2
    vis_gt_traj: True

